spring.application.name=studentManagement
server.port=8086


primary.mongodb.dbName=test-for-java-spring-boot
primary.mongodb.uri=mongodb+srv://oyunmyagmarg_db_user:g1BnnLV2kFE2Qump@cluster0.btlveka.mongodb.net/?appName=Cluster0
primary.mongodb.readPreference=primary
primary.mongodb.enableTLS=false


